### ISSUE TITLE
The example doesn't match

### ISSUE THREAD

**Issue by oneadvent** [Pylons/deformdemo#18]
The example seems to be for doing cvs, whereas the form is for requiring one or the other fields. 

The show in context looks like it lines 1341-1360

**Comment by miohtama** [comment]
Thank you for your pull request.

I am the new Deform project maintainer. I apologize the issue of this pull request not being commented earlier. Deform project is again under activate maintenance.

This is issue tracker / pull request clean to prepare a new release.

This is an old issue and I do not understand what's being discussed here. I am closing this issue to clean up the issue tracker. Please reopen with more clarifications if needed.
