### ISSUE TITLE
http://deformdemo.repoze.org/ not responding

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/deformdemo#53]
HALP!
https://downforeveryoneorjustme.com/http://deformdemo.repoze.org/

**Comment by stevepiercy** [comment]
https://downforeveryoneorjustme.com/http://deformdemo.repoze.org/

It's not responding again. Ping @ericof

**Comment by stevepiercy** [comment]
Ping also @mcdonc @tseaver 

We could move the site over to the Linode server that hosts pylonsproject.org and others, but it would be good to have a redirect set up or a DNS record pointing to a new subdomain, deformdemo.pylonsproject.org

**Comment by ericof** [comment]
Up for now, let's move it to pylonsproject.org

**Comment by tisdall** [comment]
Is it possible to forward the old URLs to the new one (since it exists out the wild)?  Also https://deformdemo.pylonsproject.org/ currently doesn't resolve for me.

**Comment by ericof** [comment]
@stevepiercy Do you control the pylonsproject domain?

**Comment by stevepiercy** [comment]
I just added a CNAME record deformdemo -> pylonsproject.org in the Linode. It might take a few minutes to resolve.

**Comment by stevepiercy** [comment]
@ericof I thought you set up deformdemo on the Linode?
