### ISSUE TITLE
deformdemo.repoze.org is down

### ISSUE THREAD

**Issue by slav0nic** [Pylons/deformdemo#58]
Looks like it already down more than one month.

**Comment by bertjwregeer** [comment]
Thanks, we will get it back up asap.

**Comment by Epithumia** [comment]
Either still down or went down again.

**Comment by slav0nic** [comment]
http://demo.substanced.net/deformdemo/ alternative

**Comment by stevepiercy** [comment]
Or build locally with [Docker](https://github.com/Pylons/deformdemo#docker-version) or from [source](https://github.com/Pylons/deformdemo#from-source).

**Comment by khorn** [comment]
Still down, apparently?

What's blocking this getting fixed?  Is it something I (or someone else) can help with?

**Comment by bertjwregeer** [comment]
Time from the Pylons Project ops team, which is three people at the moment (myself included) who all have limited time. I'll see if I can get some time to get it fixed this weekend, but I make no promises.

**Comment by khorn** [comment]
@bertjwregeer I certainly understand about limited time, and will personally appreciate any time you (or anyone else) can spare.  Thanks!

**Comment by stevepiercy** [comment]
We're back, thanks to @ergo and @bertjwregeer:

https://deformdemo.pylonsproject.org
